name: Mulgyeol Labs
title: Mulgyeol Labs
description: Mulgyeol Labs
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: taet777@naver.com
disqus_username:
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
